local opt = vim.opt

opt.clipboard = "unnamedplus"
opt.completeopt = "menu,menuone,noselect"
opt.confirm = true
opt.cursorline = true
opt.errorbells = false
opt.expandtab = true -- expand tab to spaces
opt.fillchars = {
    foldopen = "",
    foldclose = "",
    fold = " ",
    foldsep = " ",
    diff = "╱",
    eob = " ",
}
opt.grepformat = "%f:%l:%c:%m"
opt.grepprg = "rg --vimgrep --no-heading --smart-case"
opt.guicursor = "a:blinkon0"
opt.guicursor = "n-v-c:block-Cursor/lCursor,i-ci-ve:ver25-Cursor2/lCursor2,r-cr:hor20,o:hor20"
opt.history = 100
opt.ignorecase = true
opt.linebreak = true
opt.list = true
opt.listchars = {
    tab = "▸\\",
    extends = "❯",
    precedes = "❮",
    nbsp = "␣",
    trail = "·",
}
opt.mouse = "a"
opt.mousescroll = "ver:1,hor:0"
opt.number = true
opt.pumblend = 10
opt.pumheight = 10
opt.relativenumber = true
opt.ruler = false
opt.scrolloff = 5
opt.shiftround = true
opt.shiftwidth = 4 -- number of spaces to use for autoindent
opt.shortmess:append({ W = true, I = true, c = true, C = true })
opt.showmode = false
opt.signcolumn = "yes"
opt.smartcase = true
opt.smartindent = true
opt.softtabstop = 4 -- number of spaces in tab when editing
opt.spelllang = { "en" }
opt.splitbelow = true
opt.splitkeep = "screen"
opt.splitright = true
opt.swapfile = false
opt.tabstop = 4 -- number of visual spaces per TAB
opt.termguicolors = true
opt.timeoutlen = 300
opt.undofile = true
opt.updatetime = 200
opt.virtualedit = "block"
opt.visualbell = true
opt.wildmode = "longest:full,full"
opt.winblend = 0
opt.wrap = true
